### ISSUE TITLE
Feature request - padding

### ISSUE THREAD

**Issue by jimmythomson** [PoOnesNerfect/jlf#1]
I'm using the following format string:
```
{level|fg:black,bg=white} {message}\n{:key=yellow}
```
What I'd love is to be able to pad the `level` with say 10 spaces (configurable) each side. The reason for this is that it would allow me to make the log level a lot more visible when flicking through the logs.

Just as a suggestion regarding syntax:
```
{level|fg:black,bg=white,padding=10} {message}\n{:key=yellow}
```
Thanks very much!

**Comment by PoOnesNerfect** [comment]
Thanks for the suggestion!

You can already do this with `indent` like:

```
{level:black,bg=white,indent=10} {message}\n{:key=yellow}
```

**Comment by jimmythomson** [comment]
That doesn't appear to do what I was hoping for:
![image](https://github.com/user-attachments/assets/6bea07fd-67cd-4c8c-aa69-cfeffba84efb)
What I was ideally wanting was to have the white background extend out left and right, with the DEBUG text centered within that white background, with no empty space before it on the left, if that makes sense. No worries if it's not possible.
